### PR TITLE
Updated my post - reading in the railroad employment dataset

### PR DESCRIPTION
**Pull request by mohitarora18**

### CODE REVIEW

**Comment by mrolfe** [comment]
Hm, I tried deleting the post on my side and it didn't work to remove the conflicts. I would suggest copying the content of the post, deleting it entirely from your side, then add a new post with a slightly different name (or date) with the copied content. I think that should fix the conflicts.

**Comment by mohitarora18** [comment]
Hi Meredith,

Some Github Troubles:
1. I deleted the old post and created a new one. Now after I pull, commit and push, I am unable to generate a pull request. After I click on compare across forks and add my git hub repository as the head, it shows me a red cross sign below saying that it cannot automatically merge. Although it also says that "don't worry you can still create pull request", I don't see an option of doing that.
2. I thought that I should re-try knitting, pull, commit and push this post and it then might work. But I don't see these files (the r markdown and html) on the git space on R Studio anymore so that I can commit them again.
3. There is something funny going on with the date on R Markdown. When I specify tomorrow's date (08-14-2021), it knits today's date on the html post and when I specify today's date (08-13-2021), it knits yesterday's date (08-12-2021) on the html post. I wonder why that's happening.

**Comment by mrolfe** [comment]
Ugh, I think my attempts to fix things made it worse! If you are in class tomorrow, lets see if we can get this sorted out. I have an idea for just sticking specific files in the .gitignore. If that doesn't work, I'm thinking you can make a copy of the posts you want to use, throw away your old repo and refork a new one, then add your posts. There are like three of you that have persistent issues, and I suspect it is because I messed up and left you comments in the file, then when you subsequently edited them, the whole thing went kaboom (it normally would be merged anyway, so it might not be that, but I might have messed it up by trying to merge by throwing the files away...)

**Comment by sp-conway** [comment]
trying it again - sean

**Pull request closed without merging**
